services:
  - type: web
    name: linux
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://cubesai.onrender.com"
